### ISSUE TITLE
linearly increasing CPU memory usage kills the training

### ISSUE THREAD

**Issue by guochengqian** [nicolas-chaulet/torch-points3d#324]
Hi, @nicolas-chaulet 

I run KPCONV-Paper on s3dis segmentation task using: `python train.py task=segmentation model_type=kpconv model_name=KPConvPaper dataset=s3disfused training=s3dis_benchmark/kpconv training.cuda=0` . 

From wandb, I found the CPU memory usage is linearly increasing and it would eventually kill the jobs at around Epoch 200. (I have memory 250G in total). 

Could you help solve the issue? 
Thank you.

**Comment by guochengqian** [comment]
Seems the memory leak is from the S3DIS dataloader (highly because of the multi-scale dataloader). 
Since I do not have the increasing RAM issue with other experiments (like Scanet segmentation).

**Comment by nicolas-chaulet** [comment]
Interesting, I haven't seen such problem before... @loicland you ran those commands recentky right?

**Comment by nicolas-chaulet** [comment]
I checked some training from June and memory is definitely fine... Not sure what's happening, maybe Pytorch update to 1.5.1 that introduces a memory leak in the data loader?

![image](https://user-images.githubusercontent.com/3178237/87805940-0da2d180-c84e-11ea-98e8-c6e8578b3150.png)

**Comment by MukundVarmaT** [comment]
Hey, so I have often run into this issue often while using PyTorch and I really don't know why this happens. This seems to be an issue for some other people as well. Here is a link to one such issue https://github.com/pytorch/pytorch/issues/18643

**Comment by zeliu98** [comment]
I tried advice from @nicolas-chaulet, build the environment from torch-points3d v1.0.1 (https://github.com/nicolas-chaulet/torch-points3d/tree/1.0.1), and this bug disappear.

**Comment by nicolas-chaulet** [comment]
Looks like some trouble with pytorch data loader then... using pytorch 1.4
or 1.5 should solve it as well

**Comment by guochengqian** [comment]
Hello, Guys. I had the memory issue with PyTorch 1.5.
I seldom meet the same issue again when I degraded to PyTorch 1.4. (I might have the linearly increasing memory once per 10 runs, but it can be solved by simply rerun. )
 
Since this memory bug is mainly from PyTorch instead of this repo and can be partially solved by changing a PyTorch version, I choose to close this issue for now.
Thank you @nicolas-chaulet .

**Comment by nicolas-chaulet** [comment]
Thanks for the update. I hope it stabilises...

**Comment by lwx-bupt** [comment]
I suspect that it's because the Linux kernel doesn't fit with this repo, since it works fine under 5.4.0, but the bug happens when switched to 4.15.0. Nicolas used 5.3.0 and it also worked fine

**Comment by lwx-bupt** [comment]
@nicolas-chaulet I've reverted to Pytorch 1.4.0 and I hope it would be fine

**Comment by lwx-bupt** [comment]
> I tried advice from @nicolas-chaulet, build the environment from torch-points3d v1.0.1 (https://github.com/nicolas-chaulet/torch-points3d/tree/1.0.1), and this bug disappear.

Me too, perhaps it's because Pytorch 1.4.0
